// src/components/RandomTypeInfo.tsx
import React from 'react';
import { Card, CardContent } from "@/components/ui/card";

export const RandomTypeInfo: React.FC = () => {
  return (
    <Card className="shadow-none border-none">
      <CardContent className="p-4 space-y-4 text-sm text-gray-700">
        <h4 className="font-semibold text-base text-gray-800">Random Type Information</h4>
        
        <div className="space-y-2">
          <p className="font-medium text-gray-900">Standard Dice:</p>
          <p>Uses two standard 6-sided dice (1-6) with results generated by **JavaScript's `Math.random()`**. Each die face has an equal chance of appearing. The sum of the two dice creates a **natural bell-curve distribution** for totals from 2 to 12. For example, a sum of 7 appears most frequently, while 2 and 12 are the rarest. This accurately reflects real-world dice probabilities.</p>
        </div>

        <div className="space-y-2">
          <p className="font-medium text-gray-900">Visual Fair:</p>
          <p>This mode aims for a "visually fair" feel by generating sums (2-12) based on the **natural bell-curve probability of standard dice**. It uses a pre-defined list of all 36 possible two-dice outcomes, shuffles this list, and cycles through its elements. Once all elements are used, the list is re-shuffled. This approach ensures that over a cycle of 36 rolls, all sums appear with their correct real-world frequency, providing a balanced feel over short sequences.</p>
        </div>

        <div className="space-y-2">
          <p className="font-medium text-gray-900">Crypto Random:</p>
          <p>This mode employs the browser's **cryptographically secure random number generator (`window.crypto.getRandomValues()`)**. This ensures the highest level of unpredictability, making future rolls impossible to guess. Like Standard Dice, individual die rolls (1-6) are truly random, resulting in a **natural bell-curve distribution for the sums (2-12)**.</p>
        </div>

        <div className="space-y-2">
          <p className="font-medium text-gray-900">Uniform:</p>
          <p>This mode ensures that **each possible sum (from 2 to 12) appears with approximately equal frequency** over a large number of rolls. It does this by randomly picking a sum from a "pool" where all sums (2 through 12) are equally represented (each sum appears once in the pool). This creates a **flat distribution of results**, as all sums have a roughly 9.09% chance (1/11) of being rolled at any given time, unlike the natural bell-curve of standard dice.</p>
        </div>

        <div className="space-y-2">
          <p className="font-medium text-gray-900">Weighted Random:</p>
          <p>This mode generates dice sums (2-12) by picking a random value from a **fixed pool that has been weighted to match the natural bell-curve probabilities of standard dice**. Unlike "Visual Fair," this pool is not cycled or shuffled. Instead, each roll is an independent random selection from this weighted pool, aiming to consistently reflect standard dice probabilities for sums without any sequential balancing.</p>
        </div>
      </CardContent>
    </Card>
  );
};